language: node_js
before_script:
- "./node_modules/.bin/bower install"
script:
- "./node_modules/.bin/grunt karma"
cache:
  directories:
  - node_modules
  - app/bower_components
addons:
  sauce_connect: true
env:
  global:
  - secure: cXQ7a3MBWSZbYkYakloGZHrF81+ZTMaI7SWXDNyQsm84rLHPrQj/GD9GfGVZ0vK+resV9MTOmcmCQheUuhVyr8C+S7ucF50IPNcV0Dei3kZYKzy3q15ufQtIgDr0AXqmOUyEAh8E7CKaRCXVKZZ7M2m4DwqeyRC5HtvZeiZdwT8=
  - secure: OMESau5YsRJOMjnkBsC8si/avAM9mQXlwIFDnRf5h+dxqyPqIuGtpMvF+ePoUNvLHoIHNl8knoIJgmBPxh9r8YWoYQF/N9jjq75cecbRC/vIbPp3Is5sRKAmw0vpzMiOfm0lDoc4xIoqR9W4JFRr0G0TAWNdGVdZYI4b+PB2a4A=
